#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice_trm.h>

/* Pin_0 */
#define Pin_0__0__DM__MASK 0x1C0u
#define Pin_0__0__DM__SHIFT 6
#define Pin_0__0__DR CYREG_PRT1_DR
#define Pin_0__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Pin_0__0__HSIOM_MASK 0x00000F00u
#define Pin_0__0__HSIOM_SHIFT 8u
#define Pin_0__0__INTCFG CYREG_PRT1_INTCFG
#define Pin_0__0__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_0__0__MASK 0x04u
#define Pin_0__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Pin_0__0__OUT_SEL_SHIFT 4u
#define Pin_0__0__OUT_SEL_VAL 0u
#define Pin_0__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_0__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_0__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_0__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_0__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_0__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_0__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_0__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_0__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_0__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_0__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_0__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_0__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_0__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_0__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_0__0__PC CYREG_PRT1_PC
#define Pin_0__0__PC2 CYREG_PRT1_PC2
#define Pin_0__0__PORT 1u
#define Pin_0__0__PS CYREG_PRT1_PS
#define Pin_0__0__SHIFT 2
#define Pin_0__DR CYREG_PRT1_DR
#define Pin_0__INTCFG CYREG_PRT1_INTCFG
#define Pin_0__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_0__MASK 0x04u
#define Pin_0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_0__PC CYREG_PRT1_PC
#define Pin_0__PC2 CYREG_PRT1_PC2
#define Pin_0__PORT 1u
#define Pin_0__PS CYREG_PRT1_PS
#define Pin_0__sen0__DM__MASK 0x1C0u
#define Pin_0__sen0__DM__SHIFT 6
#define Pin_0__sen0__DR CYREG_PRT1_DR
#define Pin_0__sen0__INTCFG CYREG_PRT1_INTCFG
#define Pin_0__sen0__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_0__sen0__MASK 0x04u
#define Pin_0__sen0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_0__sen0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_0__sen0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_0__sen0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_0__sen0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_0__sen0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_0__sen0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_0__sen0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_0__sen0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_0__sen0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_0__sen0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_0__sen0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_0__sen0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_0__sen0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_0__sen0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_0__sen0__PC CYREG_PRT1_PC
#define Pin_0__sen0__PC2 CYREG_PRT1_PC2
#define Pin_0__sen0__PORT 1u
#define Pin_0__sen0__PS CYREG_PRT1_PS
#define Pin_0__sen0__SHIFT 2
#define Pin_0__SHIFT 2

/* Pin_1 */
#define Pin_1__0__DM__MASK 0x38u
#define Pin_1__0__DM__SHIFT 3
#define Pin_1__0__DR CYREG_PRT1_DR
#define Pin_1__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Pin_1__0__HSIOM_MASK 0x000000F0u
#define Pin_1__0__HSIOM_SHIFT 4u
#define Pin_1__0__INTCFG CYREG_PRT1_INTCFG
#define Pin_1__0__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_1__0__MASK 0x02u
#define Pin_1__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Pin_1__0__OUT_SEL_SHIFT 2u
#define Pin_1__0__OUT_SEL_VAL 0u
#define Pin_1__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_1__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_1__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_1__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_1__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_1__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_1__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_1__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_1__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_1__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_1__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_1__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_1__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_1__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_1__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_1__0__PC CYREG_PRT1_PC
#define Pin_1__0__PC2 CYREG_PRT1_PC2
#define Pin_1__0__PORT 1u
#define Pin_1__0__PS CYREG_PRT1_PS
#define Pin_1__0__SHIFT 1
#define Pin_1__DR CYREG_PRT1_DR
#define Pin_1__INTCFG CYREG_PRT1_INTCFG
#define Pin_1__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_1__MASK 0x02u
#define Pin_1__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_1__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_1__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_1__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_1__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_1__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_1__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_1__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_1__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_1__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_1__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_1__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_1__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_1__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_1__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_1__PC CYREG_PRT1_PC
#define Pin_1__PC2 CYREG_PRT1_PC2
#define Pin_1__PORT 1u
#define Pin_1__PS CYREG_PRT1_PS
#define Pin_1__sen1__DM__MASK 0x38u
#define Pin_1__sen1__DM__SHIFT 3
#define Pin_1__sen1__DR CYREG_PRT1_DR
#define Pin_1__sen1__INTCFG CYREG_PRT1_INTCFG
#define Pin_1__sen1__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_1__sen1__MASK 0x02u
#define Pin_1__sen1__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_1__sen1__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_1__sen1__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_1__sen1__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_1__sen1__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_1__sen1__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_1__sen1__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_1__sen1__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_1__sen1__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_1__sen1__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_1__sen1__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_1__sen1__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_1__sen1__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_1__sen1__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_1__sen1__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_1__sen1__PC CYREG_PRT1_PC
#define Pin_1__sen1__PC2 CYREG_PRT1_PC2
#define Pin_1__sen1__PORT 1u
#define Pin_1__sen1__PS CYREG_PRT1_PS
#define Pin_1__sen1__SHIFT 1
#define Pin_1__SHIFT 1

/* Pin_2 */
#define Pin_2__0__DM__MASK 0x07u
#define Pin_2__0__DM__SHIFT 0
#define Pin_2__0__DR CYREG_PRT1_DR
#define Pin_2__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Pin_2__0__HSIOM_MASK 0x0000000Fu
#define Pin_2__0__HSIOM_SHIFT 0u
#define Pin_2__0__INTCFG CYREG_PRT1_INTCFG
#define Pin_2__0__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_2__0__MASK 0x01u
#define Pin_2__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Pin_2__0__OUT_SEL_SHIFT 0u
#define Pin_2__0__OUT_SEL_VAL 0u
#define Pin_2__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_2__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_2__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_2__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_2__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_2__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_2__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_2__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_2__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_2__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_2__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_2__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_2__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_2__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_2__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_2__0__PC CYREG_PRT1_PC
#define Pin_2__0__PC2 CYREG_PRT1_PC2
#define Pin_2__0__PORT 1u
#define Pin_2__0__PS CYREG_PRT1_PS
#define Pin_2__0__SHIFT 0
#define Pin_2__DR CYREG_PRT1_DR
#define Pin_2__INTCFG CYREG_PRT1_INTCFG
#define Pin_2__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_2__MASK 0x01u
#define Pin_2__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_2__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_2__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_2__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_2__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_2__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_2__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_2__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_2__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_2__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_2__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_2__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_2__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_2__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_2__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_2__PC CYREG_PRT1_PC
#define Pin_2__PC2 CYREG_PRT1_PC2
#define Pin_2__PORT 1u
#define Pin_2__PS CYREG_PRT1_PS
#define Pin_2__sen2__DM__MASK 0x07u
#define Pin_2__sen2__DM__SHIFT 0
#define Pin_2__sen2__DR CYREG_PRT1_DR
#define Pin_2__sen2__INTCFG CYREG_PRT1_INTCFG
#define Pin_2__sen2__INTSTAT CYREG_PRT1_INTSTAT
#define Pin_2__sen2__MASK 0x01u
#define Pin_2__sen2__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Pin_2__sen2__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Pin_2__sen2__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Pin_2__sen2__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Pin_2__sen2__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Pin_2__sen2__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Pin_2__sen2__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Pin_2__sen2__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Pin_2__sen2__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Pin_2__sen2__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Pin_2__sen2__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Pin_2__sen2__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Pin_2__sen2__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Pin_2__sen2__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Pin_2__sen2__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Pin_2__sen2__PC CYREG_PRT1_PC
#define Pin_2__sen2__PC2 CYREG_PRT1_PC2
#define Pin_2__sen2__PORT 1u
#define Pin_2__sen2__PS CYREG_PRT1_PS
#define Pin_2__sen2__SHIFT 0
#define Pin_2__SHIFT 0

/* Pin_3 */
#define Pin_3__0__DM__MASK 0x38u
#define Pin_3__0__DM__SHIFT 3
#define Pin_3__0__DR CYREG_PRT0_DR
#define Pin_3__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Pin_3__0__HSIOM_MASK 0x000000F0u
#define Pin_3__0__HSIOM_SHIFT 4u
#define Pin_3__0__INTCFG CYREG_PRT0_INTCFG
#define Pin_3__0__INTSTAT CYREG_PRT0_INTSTAT
#define Pin_3__0__MASK 0x02u
#define Pin_3__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Pin_3__0__OUT_SEL_SHIFT 2u
#define Pin_3__0__OUT_SEL_VAL 0u
#define Pin_3__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Pin_3__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Pin_3__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Pin_3__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Pin_3__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Pin_3__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Pin_3__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Pin_3__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Pin_3__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Pin_3__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Pin_3__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Pin_3__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Pin_3__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Pin_3__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Pin_3__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Pin_3__0__PC CYREG_PRT0_PC
#define Pin_3__0__PC2 CYREG_PRT0_PC2
#define Pin_3__0__PORT 0u
#define Pin_3__0__PS CYREG_PRT0_PS
#define Pin_3__0__SHIFT 1
#define Pin_3__DR CYREG_PRT0_DR
#define Pin_3__INTCFG CYREG_PRT0_INTCFG
#define Pin_3__INTSTAT CYREG_PRT0_INTSTAT
#define Pin_3__MASK 0x02u
#define Pin_3__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Pin_3__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Pin_3__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Pin_3__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Pin_3__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Pin_3__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Pin_3__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Pin_3__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Pin_3__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Pin_3__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Pin_3__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Pin_3__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Pin_3__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Pin_3__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Pin_3__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Pin_3__PC CYREG_PRT0_PC
#define Pin_3__PC2 CYREG_PRT0_PC2
#define Pin_3__PORT 0u
#define Pin_3__PS CYREG_PRT0_PS
#define Pin_3__sen3__DM__MASK 0x38u
#define Pin_3__sen3__DM__SHIFT 3
#define Pin_3__sen3__DR CYREG_PRT0_DR
#define Pin_3__sen3__INTCFG CYREG_PRT0_INTCFG
#define Pin_3__sen3__INTSTAT CYREG_PRT0_INTSTAT
#define Pin_3__sen3__MASK 0x02u
#define Pin_3__sen3__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Pin_3__sen3__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Pin_3__sen3__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Pin_3__sen3__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Pin_3__sen3__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Pin_3__sen3__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Pin_3__sen3__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Pin_3__sen3__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Pin_3__sen3__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Pin_3__sen3__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Pin_3__sen3__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Pin_3__sen3__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Pin_3__sen3__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Pin_3__sen3__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Pin_3__sen3__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Pin_3__sen3__PC CYREG_PRT0_PC
#define Pin_3__sen3__PC2 CYREG_PRT0_PC2
#define Pin_3__sen3__PORT 0u
#define Pin_3__sen3__PS CYREG_PRT0_PS
#define Pin_3__sen3__SHIFT 1
#define Pin_3__SHIFT 1

/* Pin_4 */
#define Pin_4__0__DM__MASK 0x07u
#define Pin_4__0__DM__SHIFT 0
#define Pin_4__0__DR CYREG_PRT0_DR
#define Pin_4__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Pin_4__0__HSIOM_MASK 0x0000000Fu
#define Pin_4__0__HSIOM_SHIFT 0u
#define Pin_4__0__INTCFG CYREG_PRT0_INTCFG
#define Pin_4__0__INTSTAT CYREG_PRT0_INTSTAT
#define Pin_4__0__MASK 0x01u
#define Pin_4__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Pin_4__0__OUT_SEL_SHIFT 0u
#define Pin_4__0__OUT_SEL_VAL 0u
#define Pin_4__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Pin_4__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Pin_4__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Pin_4__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Pin_4__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Pin_4__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Pin_4__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Pin_4__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Pin_4__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Pin_4__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Pin_4__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Pin_4__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Pin_4__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Pin_4__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Pin_4__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Pin_4__0__PC CYREG_PRT0_PC
#define Pin_4__0__PC2 CYREG_PRT0_PC2
#define Pin_4__0__PORT 0u
#define Pin_4__0__PS CYREG_PRT0_PS
#define Pin_4__0__SHIFT 0
#define Pin_4__DR CYREG_PRT0_DR
#define Pin_4__INTCFG CYREG_PRT0_INTCFG
#define Pin_4__INTSTAT CYREG_PRT0_INTSTAT
#define Pin_4__MASK 0x01u
#define Pin_4__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Pin_4__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Pin_4__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Pin_4__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Pin_4__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Pin_4__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Pin_4__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Pin_4__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Pin_4__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Pin_4__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Pin_4__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Pin_4__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Pin_4__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Pin_4__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Pin_4__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Pin_4__PC CYREG_PRT0_PC
#define Pin_4__PC2 CYREG_PRT0_PC2
#define Pin_4__PORT 0u
#define Pin_4__PS CYREG_PRT0_PS
#define Pin_4__sen4__DM__MASK 0x07u
#define Pin_4__sen4__DM__SHIFT 0
#define Pin_4__sen4__DR CYREG_PRT0_DR
#define Pin_4__sen4__INTCFG CYREG_PRT0_INTCFG
#define Pin_4__sen4__INTSTAT CYREG_PRT0_INTSTAT
#define Pin_4__sen4__MASK 0x01u
#define Pin_4__sen4__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Pin_4__sen4__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Pin_4__sen4__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Pin_4__sen4__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Pin_4__sen4__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Pin_4__sen4__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Pin_4__sen4__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Pin_4__sen4__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Pin_4__sen4__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Pin_4__sen4__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Pin_4__sen4__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Pin_4__sen4__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Pin_4__sen4__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Pin_4__sen4__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Pin_4__sen4__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Pin_4__sen4__PC CYREG_PRT0_PC
#define Pin_4__sen4__PC2 CYREG_PRT0_PC2
#define Pin_4__sen4__PORT 0u
#define Pin_4__sen4__PS CYREG_PRT0_PS
#define Pin_4__sen4__SHIFT 0
#define Pin_4__SHIFT 0

/* Pin_5 */
#define Pin_5__0__DM__MASK 0x38000u
#define Pin_5__0__DM__SHIFT 15
#define Pin_5__0__DR CYREG_PRT2_DR
#define Pin_5__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Pin_5__0__HSIOM_MASK 0x00F00000u
#define Pin_5__0__HSIOM_SHIFT 20u
#define Pin_5__0__INTCFG CYREG_PRT2_INTCFG
#define Pin_5__0__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_5__0__MASK 0x20u
#define Pin_5__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Pin_5__0__OUT_SEL_SHIFT 10u
#define Pin_5__0__OUT_SEL_VAL 1u
#define Pin_5__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_5__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_5__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_5__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_5__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_5__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_5__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_5__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_5__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_5__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_5__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_5__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_5__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_5__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_5__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_5__0__PC CYREG_PRT2_PC
#define Pin_5__0__PC2 CYREG_PRT2_PC2
#define Pin_5__0__PORT 2u
#define Pin_5__0__PS CYREG_PRT2_PS
#define Pin_5__0__SHIFT 5
#define Pin_5__DR CYREG_PRT2_DR
#define Pin_5__INTCFG CYREG_PRT2_INTCFG
#define Pin_5__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_5__MASK 0x20u
#define Pin_5__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_5__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_5__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_5__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_5__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_5__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_5__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_5__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_5__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_5__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_5__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_5__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_5__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_5__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_5__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_5__PC CYREG_PRT2_PC
#define Pin_5__PC2 CYREG_PRT2_PC2
#define Pin_5__PORT 2u
#define Pin_5__PS CYREG_PRT2_PS
#define Pin_5__sen5__DM__MASK 0x38000u
#define Pin_5__sen5__DM__SHIFT 15
#define Pin_5__sen5__DR CYREG_PRT2_DR
#define Pin_5__sen5__INTCFG CYREG_PRT2_INTCFG
#define Pin_5__sen5__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_5__sen5__MASK 0x20u
#define Pin_5__sen5__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_5__sen5__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_5__sen5__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_5__sen5__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_5__sen5__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_5__sen5__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_5__sen5__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_5__sen5__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_5__sen5__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_5__sen5__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_5__sen5__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_5__sen5__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_5__sen5__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_5__sen5__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_5__sen5__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_5__sen5__PC CYREG_PRT2_PC
#define Pin_5__sen5__PC2 CYREG_PRT2_PC2
#define Pin_5__sen5__PORT 2u
#define Pin_5__sen5__PS CYREG_PRT2_PS
#define Pin_5__sen5__SHIFT 5
#define Pin_5__SHIFT 5

/* Pin_6 */
#define Pin_6__0__DM__MASK 0x7000u
#define Pin_6__0__DM__SHIFT 12
#define Pin_6__0__DR CYREG_PRT2_DR
#define Pin_6__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Pin_6__0__HSIOM_MASK 0x000F0000u
#define Pin_6__0__HSIOM_SHIFT 16u
#define Pin_6__0__INTCFG CYREG_PRT2_INTCFG
#define Pin_6__0__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_6__0__MASK 0x10u
#define Pin_6__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Pin_6__0__OUT_SEL_SHIFT 8u
#define Pin_6__0__OUT_SEL_VAL 1u
#define Pin_6__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_6__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_6__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_6__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_6__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_6__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_6__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_6__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_6__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_6__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_6__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_6__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_6__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_6__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_6__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_6__0__PC CYREG_PRT2_PC
#define Pin_6__0__PC2 CYREG_PRT2_PC2
#define Pin_6__0__PORT 2u
#define Pin_6__0__PS CYREG_PRT2_PS
#define Pin_6__0__SHIFT 4
#define Pin_6__DR CYREG_PRT2_DR
#define Pin_6__INTCFG CYREG_PRT2_INTCFG
#define Pin_6__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_6__MASK 0x10u
#define Pin_6__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_6__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_6__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_6__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_6__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_6__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_6__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_6__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_6__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_6__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_6__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_6__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_6__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_6__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_6__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_6__PC CYREG_PRT2_PC
#define Pin_6__PC2 CYREG_PRT2_PC2
#define Pin_6__PORT 2u
#define Pin_6__PS CYREG_PRT2_PS
#define Pin_6__sen6__DM__MASK 0x7000u
#define Pin_6__sen6__DM__SHIFT 12
#define Pin_6__sen6__DR CYREG_PRT2_DR
#define Pin_6__sen6__INTCFG CYREG_PRT2_INTCFG
#define Pin_6__sen6__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_6__sen6__MASK 0x10u
#define Pin_6__sen6__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_6__sen6__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_6__sen6__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_6__sen6__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_6__sen6__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_6__sen6__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_6__sen6__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_6__sen6__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_6__sen6__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_6__sen6__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_6__sen6__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_6__sen6__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_6__sen6__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_6__sen6__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_6__sen6__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_6__sen6__PC CYREG_PRT2_PC
#define Pin_6__sen6__PC2 CYREG_PRT2_PC2
#define Pin_6__sen6__PORT 2u
#define Pin_6__sen6__PS CYREG_PRT2_PS
#define Pin_6__sen6__SHIFT 4
#define Pin_6__SHIFT 4

/* Pin_7 */
#define Pin_7__0__DM__MASK 0xE00u
#define Pin_7__0__DM__SHIFT 9
#define Pin_7__0__DR CYREG_PRT2_DR
#define Pin_7__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Pin_7__0__HSIOM_MASK 0x0000F000u
#define Pin_7__0__HSIOM_SHIFT 12u
#define Pin_7__0__INTCFG CYREG_PRT2_INTCFG
#define Pin_7__0__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_7__0__MASK 0x08u
#define Pin_7__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define Pin_7__0__OUT_SEL_SHIFT 6u
#define Pin_7__0__OUT_SEL_VAL 2u
#define Pin_7__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_7__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_7__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_7__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_7__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_7__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_7__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_7__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_7__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_7__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_7__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_7__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_7__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_7__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_7__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_7__0__PC CYREG_PRT2_PC
#define Pin_7__0__PC2 CYREG_PRT2_PC2
#define Pin_7__0__PORT 2u
#define Pin_7__0__PS CYREG_PRT2_PS
#define Pin_7__0__SHIFT 3
#define Pin_7__DR CYREG_PRT2_DR
#define Pin_7__INTCFG CYREG_PRT2_INTCFG
#define Pin_7__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_7__MASK 0x08u
#define Pin_7__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_7__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_7__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_7__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_7__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_7__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_7__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_7__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_7__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_7__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_7__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_7__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_7__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_7__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_7__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_7__PC CYREG_PRT2_PC
#define Pin_7__PC2 CYREG_PRT2_PC2
#define Pin_7__PORT 2u
#define Pin_7__PS CYREG_PRT2_PS
#define Pin_7__sen7__DM__MASK 0xE00u
#define Pin_7__sen7__DM__SHIFT 9
#define Pin_7__sen7__DR CYREG_PRT2_DR
#define Pin_7__sen7__INTCFG CYREG_PRT2_INTCFG
#define Pin_7__sen7__INTSTAT CYREG_PRT2_INTSTAT
#define Pin_7__sen7__MASK 0x08u
#define Pin_7__sen7__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Pin_7__sen7__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Pin_7__sen7__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Pin_7__sen7__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Pin_7__sen7__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Pin_7__sen7__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Pin_7__sen7__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Pin_7__sen7__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Pin_7__sen7__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Pin_7__sen7__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Pin_7__sen7__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Pin_7__sen7__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Pin_7__sen7__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Pin_7__sen7__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Pin_7__sen7__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Pin_7__sen7__PC CYREG_PRT2_PC
#define Pin_7__sen7__PC2 CYREG_PRT2_PC2
#define Pin_7__sen7__PORT 2u
#define Pin_7__sen7__PS CYREG_PRT2_PS
#define Pin_7__sen7__SHIFT 3
#define Pin_7__SHIFT 3

/* Tx_06 */
#define Tx_06__0__DM__MASK 0x1C0000u
#define Tx_06__0__DM__SHIFT 18
#define Tx_06__0__DR CYREG_PRT0_DR
#define Tx_06__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Tx_06__0__HSIOM_MASK 0x0F000000u
#define Tx_06__0__HSIOM_SHIFT 24u
#define Tx_06__0__INTCFG CYREG_PRT0_INTCFG
#define Tx_06__0__INTSTAT CYREG_PRT0_INTSTAT
#define Tx_06__0__MASK 0x40u
#define Tx_06__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Tx_06__0__OUT_SEL_SHIFT 12u
#define Tx_06__0__OUT_SEL_VAL 1u
#define Tx_06__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Tx_06__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Tx_06__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Tx_06__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Tx_06__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Tx_06__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Tx_06__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Tx_06__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Tx_06__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Tx_06__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Tx_06__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Tx_06__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Tx_06__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Tx_06__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Tx_06__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Tx_06__0__PC CYREG_PRT0_PC
#define Tx_06__0__PC2 CYREG_PRT0_PC2
#define Tx_06__0__PORT 0u
#define Tx_06__0__PS CYREG_PRT0_PS
#define Tx_06__0__SHIFT 6
#define Tx_06__DR CYREG_PRT0_DR
#define Tx_06__INTCFG CYREG_PRT0_INTCFG
#define Tx_06__INTSTAT CYREG_PRT0_INTSTAT
#define Tx_06__MASK 0x40u
#define Tx_06__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Tx_06__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Tx_06__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Tx_06__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Tx_06__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Tx_06__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Tx_06__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Tx_06__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Tx_06__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Tx_06__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Tx_06__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Tx_06__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Tx_06__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Tx_06__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Tx_06__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Tx_06__PC CYREG_PRT0_PC
#define Tx_06__PC2 CYREG_PRT0_PC2
#define Tx_06__PORT 0u
#define Tx_06__PS CYREG_PRT0_PS
#define Tx_06__SHIFT 6
#define Tx_06__UART_Tx__DM__MASK 0x1C0000u
#define Tx_06__UART_Tx__DM__SHIFT 18
#define Tx_06__UART_Tx__DR CYREG_PRT0_DR
#define Tx_06__UART_Tx__INTCFG CYREG_PRT0_INTCFG
#define Tx_06__UART_Tx__INTSTAT CYREG_PRT0_INTSTAT
#define Tx_06__UART_Tx__MASK 0x40u
#define Tx_06__UART_Tx__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Tx_06__UART_Tx__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Tx_06__UART_Tx__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Tx_06__UART_Tx__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Tx_06__UART_Tx__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Tx_06__UART_Tx__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Tx_06__UART_Tx__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Tx_06__UART_Tx__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Tx_06__UART_Tx__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Tx_06__UART_Tx__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Tx_06__UART_Tx__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Tx_06__UART_Tx__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Tx_06__UART_Tx__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Tx_06__UART_Tx__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Tx_06__UART_Tx__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Tx_06__UART_Tx__PC CYREG_PRT0_PC
#define Tx_06__UART_Tx__PC2 CYREG_PRT0_PC2
#define Tx_06__UART_Tx__PORT 0u
#define Tx_06__UART_Tx__PS CYREG_PRT0_PS
#define Tx_06__UART_Tx__SHIFT 6

/* PinLED */
#define PinLED__0__DM__MASK 0x1C0u
#define PinLED__0__DM__SHIFT 6
#define PinLED__0__DR CYREG_PRT0_DR
#define PinLED__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define PinLED__0__HSIOM_MASK 0x00000F00u
#define PinLED__0__HSIOM_SHIFT 8u
#define PinLED__0__INTCFG CYREG_PRT0_INTCFG
#define PinLED__0__INTSTAT CYREG_PRT0_INTSTAT
#define PinLED__0__MASK 0x04u
#define PinLED__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define PinLED__0__OUT_SEL_SHIFT 4u
#define PinLED__0__OUT_SEL_VAL 3u
#define PinLED__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define PinLED__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define PinLED__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define PinLED__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define PinLED__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define PinLED__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define PinLED__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define PinLED__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define PinLED__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define PinLED__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define PinLED__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define PinLED__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define PinLED__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define PinLED__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define PinLED__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define PinLED__0__PC CYREG_PRT0_PC
#define PinLED__0__PC2 CYREG_PRT0_PC2
#define PinLED__0__PORT 0u
#define PinLED__0__PS CYREG_PRT0_PS
#define PinLED__0__SHIFT 2
#define PinLED__DR CYREG_PRT0_DR
#define PinLED__INTCFG CYREG_PRT0_INTCFG
#define PinLED__INTSTAT CYREG_PRT0_INTSTAT
#define PinLED__LED__DM__MASK 0x1C0u
#define PinLED__LED__DM__SHIFT 6
#define PinLED__LED__DR CYREG_PRT0_DR
#define PinLED__LED__INTCFG CYREG_PRT0_INTCFG
#define PinLED__LED__INTSTAT CYREG_PRT0_INTSTAT
#define PinLED__LED__MASK 0x04u
#define PinLED__LED__PA__CFG0 CYREG_UDB_PA0_CFG0
#define PinLED__LED__PA__CFG1 CYREG_UDB_PA0_CFG1
#define PinLED__LED__PA__CFG10 CYREG_UDB_PA0_CFG10
#define PinLED__LED__PA__CFG11 CYREG_UDB_PA0_CFG11
#define PinLED__LED__PA__CFG12 CYREG_UDB_PA0_CFG12
#define PinLED__LED__PA__CFG13 CYREG_UDB_PA0_CFG13
#define PinLED__LED__PA__CFG14 CYREG_UDB_PA0_CFG14
#define PinLED__LED__PA__CFG2 CYREG_UDB_PA0_CFG2
#define PinLED__LED__PA__CFG3 CYREG_UDB_PA0_CFG3
#define PinLED__LED__PA__CFG4 CYREG_UDB_PA0_CFG4
#define PinLED__LED__PA__CFG5 CYREG_UDB_PA0_CFG5
#define PinLED__LED__PA__CFG6 CYREG_UDB_PA0_CFG6
#define PinLED__LED__PA__CFG7 CYREG_UDB_PA0_CFG7
#define PinLED__LED__PA__CFG8 CYREG_UDB_PA0_CFG8
#define PinLED__LED__PA__CFG9 CYREG_UDB_PA0_CFG9
#define PinLED__LED__PC CYREG_PRT0_PC
#define PinLED__LED__PC2 CYREG_PRT0_PC2
#define PinLED__LED__PORT 0u
#define PinLED__LED__PS CYREG_PRT0_PS
#define PinLED__LED__SHIFT 2
#define PinLED__MASK 0x04u
#define PinLED__PA__CFG0 CYREG_UDB_PA0_CFG0
#define PinLED__PA__CFG1 CYREG_UDB_PA0_CFG1
#define PinLED__PA__CFG10 CYREG_UDB_PA0_CFG10
#define PinLED__PA__CFG11 CYREG_UDB_PA0_CFG11
#define PinLED__PA__CFG12 CYREG_UDB_PA0_CFG12
#define PinLED__PA__CFG13 CYREG_UDB_PA0_CFG13
#define PinLED__PA__CFG14 CYREG_UDB_PA0_CFG14
#define PinLED__PA__CFG2 CYREG_UDB_PA0_CFG2
#define PinLED__PA__CFG3 CYREG_UDB_PA0_CFG3
#define PinLED__PA__CFG4 CYREG_UDB_PA0_CFG4
#define PinLED__PA__CFG5 CYREG_UDB_PA0_CFG5
#define PinLED__PA__CFG6 CYREG_UDB_PA0_CFG6
#define PinLED__PA__CFG7 CYREG_UDB_PA0_CFG7
#define PinLED__PA__CFG8 CYREG_UDB_PA0_CFG8
#define PinLED__PA__CFG9 CYREG_UDB_PA0_CFG9
#define PinLED__PC CYREG_PRT0_PC
#define PinLED__PC2 CYREG_PRT0_PC2
#define PinLED__PORT 0u
#define PinLED__PS CYREG_PRT0_PS
#define PinLED__SHIFT 2

/* UART_1_BUART */
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__A0_A1_REG CYREG_UDB_CAT16_A_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__A0_REG CYREG_UDB_W8_A0_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__A1_REG CYREG_UDB_W8_A1_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__D0_D1_REG CYREG_UDB_CAT16_D_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__D0_REG CYREG_UDB_W8_D0_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__D1_REG CYREG_UDB_W8_D1_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__F0_F1_REG CYREG_UDB_CAT16_F_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__F0_REG CYREG_UDB_W8_F0_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__F1_REG CYREG_UDB_W8_F1_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_03
#define UART_1_BUART_sTX_sCLOCK_TxBitClkGen__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_03
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_A0_REG CYREG_UDB_W16_A0_02
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_A1_REG CYREG_UDB_W16_A1_02
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_D0_REG CYREG_UDB_W16_D0_02
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_D1_REG CYREG_UDB_W16_D1_02
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_F0_REG CYREG_UDB_W16_F0_02
#define UART_1_BUART_sTX_TxShifter_u0__16BIT_F1_REG CYREG_UDB_W16_F1_02
#define UART_1_BUART_sTX_TxShifter_u0__A0_A1_REG CYREG_UDB_CAT16_A_02
#define UART_1_BUART_sTX_TxShifter_u0__A0_REG CYREG_UDB_W8_A0_02
#define UART_1_BUART_sTX_TxShifter_u0__A1_REG CYREG_UDB_W8_A1_02
#define UART_1_BUART_sTX_TxShifter_u0__D0_D1_REG CYREG_UDB_CAT16_D_02
#define UART_1_BUART_sTX_TxShifter_u0__D0_REG CYREG_UDB_W8_D0_02
#define UART_1_BUART_sTX_TxShifter_u0__D1_REG CYREG_UDB_W8_D1_02
#define UART_1_BUART_sTX_TxShifter_u0__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define UART_1_BUART_sTX_TxShifter_u0__F0_F1_REG CYREG_UDB_CAT16_F_02
#define UART_1_BUART_sTX_TxShifter_u0__F0_REG CYREG_UDB_W8_F0_02
#define UART_1_BUART_sTX_TxShifter_u0__F1_REG CYREG_UDB_W8_F1_02
#define UART_1_BUART_sTX_TxShifter_u0__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define UART_1_BUART_sTX_TxShifter_u0__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define UART_1_BUART_sTX_TxSts__0__MASK 0x01u
#define UART_1_BUART_sTX_TxSts__0__POS 0
#define UART_1_BUART_sTX_TxSts__1__MASK 0x02u
#define UART_1_BUART_sTX_TxSts__1__POS 1
#define UART_1_BUART_sTX_TxSts__16BIT_STATUS_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define UART_1_BUART_sTX_TxSts__16BIT_STATUS_REG CYREG_UDB_W16_ST_02
#define UART_1_BUART_sTX_TxSts__2__MASK 0x04u
#define UART_1_BUART_sTX_TxSts__2__POS 2
#define UART_1_BUART_sTX_TxSts__3__MASK 0x08u
#define UART_1_BUART_sTX_TxSts__3__POS 3
#define UART_1_BUART_sTX_TxSts__MASK 0x0Fu
#define UART_1_BUART_sTX_TxSts__MASK_REG CYREG_UDB_W8_MSK_02
#define UART_1_BUART_sTX_TxSts__MASK_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define UART_1_BUART_sTX_TxSts__PER_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define UART_1_BUART_sTX_TxSts__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define UART_1_BUART_sTX_TxSts__STATUS_CNT_REG CYREG_UDB_CAT16_CTL_ST_02
#define UART_1_BUART_sTX_TxSts__STATUS_CONTROL_REG CYREG_UDB_CAT16_CTL_ST_02
#define UART_1_BUART_sTX_TxSts__STATUS_REG CYREG_UDB_W8_ST_02

/* UART_1_TXInternalInterrupt */
#define UART_1_TXInternalInterrupt__INTC_CLR_EN_REG CYREG_CM0_ICER
#define UART_1_TXInternalInterrupt__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define UART_1_TXInternalInterrupt__INTC_MASK 0x04u
#define UART_1_TXInternalInterrupt__INTC_NUMBER 2u
#define UART_1_TXInternalInterrupt__INTC_PRIOR_MASK 0xC00000u
#define UART_1_TXInternalInterrupt__INTC_PRIOR_NUM 3u
#define UART_1_TXInternalInterrupt__INTC_PRIOR_REG CYREG_CM0_IPR0
#define UART_1_TXInternalInterrupt__INTC_SET_EN_REG CYREG_CM0_ISER
#define UART_1_TXInternalInterrupt__INTC_SET_PD_REG CYREG_CM0_ISPR

/* OneWire_clock_delay */
#define OneWire_clock_delay__DIVIDER_MASK 0x0000FFFFu
#define OneWire_clock_delay__ENABLE CYREG_CLK_DIVIDER_B00
#define OneWire_clock_delay__ENABLE_MASK 0x80000000u
#define OneWire_clock_delay__MASK 0x80000000u
#define OneWire_clock_delay__REGISTER CYREG_CLK_DIVIDER_B00

/* OneWire_ControlReg_DRV */
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__0__MASK 0x01u
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__0__POS 0
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__CONTROL_REG CYREG_UDB_W8_CTL_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__COUNT_REG CYREG_UDB_W8_CTL_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__MASK 0x01u
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_03
#define OneWire_ControlReg_DRV_Sync_ctrl_reg__PERIOD_REG CYREG_UDB_W8_MSK_03

/* OneWire_ControlReg_SEL */
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__0__MASK 0x01u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__0__POS 0
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__1__MASK 0x02u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__1__POS 1
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__2__MASK 0x04u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__2__POS 2
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__3__MASK 0x08u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__3__POS 3
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__4__MASK 0x10u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__4__POS 4
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__5__MASK 0x20u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__5__POS 5
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__6__MASK 0x40u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__6__POS 6
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__7__MASK 0x80u
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__7__POS 7
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__CONTROL_REG CYREG_UDB_W8_CTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__COUNT_REG CYREG_UDB_W8_CTL_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__MASK 0xFFu
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define OneWire_ControlReg_SEL_Sync_ctrl_reg__PERIOD_REG CYREG_UDB_W8_MSK_02

/* OneWire_isr_DataReady */
#define OneWire_isr_DataReady__INTC_CLR_EN_REG CYREG_CM0_ICER
#define OneWire_isr_DataReady__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define OneWire_isr_DataReady__INTC_MASK 0x01u
#define OneWire_isr_DataReady__INTC_NUMBER 0u
#define OneWire_isr_DataReady__INTC_PRIOR_MASK 0xC0u
#define OneWire_isr_DataReady__INTC_PRIOR_NUM 3u
#define OneWire_isr_DataReady__INTC_PRIOR_REG CYREG_CM0_IPR0
#define OneWire_isr_DataReady__INTC_SET_EN_REG CYREG_CM0_ISER
#define OneWire_isr_DataReady__INTC_SET_PD_REG CYREG_CM0_ISPR

/* OneWire_StatusReg_BUS */
#define OneWire_StatusReg_BUS_sts_sts_reg__0__MASK 0x01u
#define OneWire_StatusReg_BUS_sts_sts_reg__0__POS 0
#define OneWire_StatusReg_BUS_sts_sts_reg__1__MASK 0x02u
#define OneWire_StatusReg_BUS_sts_sts_reg__1__POS 1
#define OneWire_StatusReg_BUS_sts_sts_reg__16BIT_STATUS_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define OneWire_StatusReg_BUS_sts_sts_reg__16BIT_STATUS_REG CYREG_UDB_W16_ST_01
#define OneWire_StatusReg_BUS_sts_sts_reg__2__MASK 0x04u
#define OneWire_StatusReg_BUS_sts_sts_reg__2__POS 2
#define OneWire_StatusReg_BUS_sts_sts_reg__3__MASK 0x08u
#define OneWire_StatusReg_BUS_sts_sts_reg__3__POS 3
#define OneWire_StatusReg_BUS_sts_sts_reg__4__MASK 0x10u
#define OneWire_StatusReg_BUS_sts_sts_reg__4__POS 4
#define OneWire_StatusReg_BUS_sts_sts_reg__5__MASK 0x20u
#define OneWire_StatusReg_BUS_sts_sts_reg__5__POS 5
#define OneWire_StatusReg_BUS_sts_sts_reg__6__MASK 0x40u
#define OneWire_StatusReg_BUS_sts_sts_reg__6__POS 6
#define OneWire_StatusReg_BUS_sts_sts_reg__7__MASK 0x80u
#define OneWire_StatusReg_BUS_sts_sts_reg__7__POS 7
#define OneWire_StatusReg_BUS_sts_sts_reg__MASK 0xFFu
#define OneWire_StatusReg_BUS_sts_sts_reg__MASK_REG CYREG_UDB_W8_MSK_01
#define OneWire_StatusReg_BUS_sts_sts_reg__MASK_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define OneWire_StatusReg_BUS_sts_sts_reg__PER_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define OneWire_StatusReg_BUS_sts_sts_reg__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define OneWire_StatusReg_BUS_sts_sts_reg__STATUS_CNT_REG CYREG_UDB_CAT16_CTL_ST_01
#define OneWire_StatusReg_BUS_sts_sts_reg__STATUS_CONTROL_REG CYREG_UDB_CAT16_CTL_ST_01
#define OneWire_StatusReg_BUS_sts_sts_reg__STATUS_REG CYREG_UDB_W8_ST_01

/* OneWire_TimerDelay_TimerUDB */
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__0__MASK 0x01u
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__0__POS 0
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__16BIT_STATUS_AUX_CTL_REG CYREG_UDB_W16_ACTL_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__16BIT_STATUS_REG CYREG_UDB_W16_ST_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__2__MASK 0x04u
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__2__POS 2
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__3__MASK 0x08u
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__3__POS 3
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__32BIT_MASK_REG CYREG_UDB_W32_MSK_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__32BIT_STATUS_AUX_CTL_REG CYREG_UDB_W32_ACTL_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__32BIT_STATUS_REG CYREG_UDB_W32_ST_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__MASK 0x0Du
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__MASK_REG CYREG_UDB_W8_MSK_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__MASK_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__PER_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__STATUS_CNT_REG CYREG_UDB_CAT16_CTL_ST_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__STATUS_CONTROL_REG CYREG_UDB_CAT16_CTL_ST_00
#define OneWire_TimerDelay_TimerUDB_rstSts_stsreg__STATUS_REG CYREG_UDB_W8_ST_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__32BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W32_ACTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__32BIT_CONTROL_REG CYREG_UDB_W32_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__32BIT_COUNT_REG CYREG_UDB_W32_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__32BIT_PERIOD_REG CYREG_UDB_W32_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__4__MASK 0x10u
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__4__POS 4
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__7__MASK 0x80u
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__7__POS 7
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_REG CYREG_UDB_W8_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_REG CYREG_UDB_W8_CTL_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__MASK 0x90u
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define OneWire_TimerDelay_TimerUDB_sCTRLReg_SyncCtl_ctrlreg__PERIOD_REG CYREG_UDB_W8_MSK_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_A0_REG CYREG_UDB_W16_A0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_A1_REG CYREG_UDB_W16_A1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_D0_REG CYREG_UDB_W16_D0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_D1_REG CYREG_UDB_W16_D1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_F0_REG CYREG_UDB_W16_F0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__16BIT_F1_REG CYREG_UDB_W16_F1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_A0_REG CYREG_UDB_W32_A0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_A1_REG CYREG_UDB_W32_A1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_D0_REG CYREG_UDB_W32_D0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_D1_REG CYREG_UDB_W32_D1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_DP_AUX_CTL_REG CYREG_UDB_W32_ACTL_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_F0_REG CYREG_UDB_W32_F0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__32BIT_F1_REG CYREG_UDB_W32_F1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__A0_A1_REG CYREG_UDB_CAT16_A_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__A0_REG CYREG_UDB_W8_A0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__A1_REG CYREG_UDB_W8_A1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__D0_D1_REG CYREG_UDB_CAT16_D_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__D0_REG CYREG_UDB_W8_D0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__D1_REG CYREG_UDB_W8_D1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__F0_F1_REG CYREG_UDB_CAT16_F_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__F0_REG CYREG_UDB_W8_F0_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__F1_REG CYREG_UDB_W8_F1_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u0__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_00
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_A0_REG CYREG_UDB_W16_A0_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_A1_REG CYREG_UDB_W16_A1_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_D0_REG CYREG_UDB_W16_D0_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_D1_REG CYREG_UDB_W16_D1_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_F0_REG CYREG_UDB_W16_F0_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__16BIT_F1_REG CYREG_UDB_W16_F1_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__A0_A1_REG CYREG_UDB_CAT16_A_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__A0_REG CYREG_UDB_W8_A0_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__A1_REG CYREG_UDB_W8_A1_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__D0_D1_REG CYREG_UDB_CAT16_D_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__D0_REG CYREG_UDB_W8_D0_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__D1_REG CYREG_UDB_W8_D1_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__F0_F1_REG CYREG_UDB_CAT16_F_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__F0_REG CYREG_UDB_W8_F0_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__F1_REG CYREG_UDB_W8_F1_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define OneWire_TimerDelay_TimerUDB_sT16_timerdp_u1__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01

/* OneWire_Trigger */
#define OneWire_Trigger_Sync_ctrl_reg__0__MASK 0x01u
#define OneWire_Trigger_Sync_ctrl_reg__0__POS 0
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_01
#define OneWire_Trigger_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_01
#define OneWire_Trigger_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define OneWire_Trigger_Sync_ctrl_reg__CONTROL_REG CYREG_UDB_W8_CTL_01
#define OneWire_Trigger_Sync_ctrl_reg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_01
#define OneWire_Trigger_Sync_ctrl_reg__COUNT_REG CYREG_UDB_W8_CTL_01
#define OneWire_Trigger_Sync_ctrl_reg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_01
#define OneWire_Trigger_Sync_ctrl_reg__MASK 0x01u
#define OneWire_Trigger_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define OneWire_Trigger_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define OneWire_Trigger_Sync_ctrl_reg__PERIOD_REG CYREG_UDB_W8_MSK_01

/* isr_Timer */
#define isr_Timer__INTC_CLR_EN_REG CYREG_CM0_ICER
#define isr_Timer__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define isr_Timer__INTC_MASK 0x08u
#define isr_Timer__INTC_NUMBER 3u
#define isr_Timer__INTC_PRIOR_MASK 0xC0000000u
#define isr_Timer__INTC_PRIOR_NUM 3u
#define isr_Timer__INTC_PRIOR_REG CYREG_CM0_IPR0
#define isr_Timer__INTC_SET_EN_REG CYREG_CM0_ISER
#define isr_Timer__INTC_SET_PD_REG CYREG_CM0_ISPR

/* Clock_UART */
#define Clock_UART__DIVIDER_MASK 0x0000FFFFu
#define Clock_UART__ENABLE CYREG_CLK_DIVIDER_A00
#define Clock_UART__ENABLE_MASK 0x80000000u
#define Clock_UART__MASK 0x80000000u
#define Clock_UART__REGISTER CYREG_CLK_DIVIDER_A00

/* Clock_ReportTimer */
#define Clock_ReportTimer__DIVIDER_MASK 0x0000FFFFu
#define Clock_ReportTimer__ENABLE CYREG_CLK_DIVIDER_B01
#define Clock_ReportTimer__ENABLE_MASK 0x80000000u
#define Clock_ReportTimer__MASK 0x80000000u
#define Clock_ReportTimer__REGISTER CYREG_CLK_DIVIDER_B01

/* Miscellaneous */
#define CY_VERSION "PSoC Creator  3.1 SP1"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 6u
#define CYDEV_CHIP_DIE_PSOC4A 3u
#define CYDEV_CHIP_DIE_PSOC5LP 5u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 3u
#define CYDEV_CHIP_MEMBER_4D 2u
#define CYDEV_CHIP_MEMBER_4F 4u
#define CYDEV_CHIP_MEMBER_5A 6u
#define CYDEV_CHIP_MEMBER_5B 5u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0400
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5.0
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5.0
#define CYDEV_VDDD_MV 5000
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
